"""Offline route evaluation for the V1 three-channel Planner.

Calls `orchestration.planner.plan_request` directly. No Ollama, no network, no
database, no retrieval - the planner is pure, so this evaluator is too, and its
results are deterministic.

The expected labels in the dataset are human-authored intent labels. They were
never generated by running this planner, so a mismatch is a finding about the
planner, not a defect in the dataset.

Usage:
    python evaluate_orchestrated_routes.py --dataset <file> --output <file>
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import subprocess
import sys
from collections import Counter, defaultdict
from pathlib import Path

from orchestration.planner import ROUTE_BY_STEPS, Route, plan_request

# The datasets are Chinese. On a GBK console the report would be unreadable and
# a redirected transcript would be mojibake, so force UTF-8 on this stream only.
for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8")
    except (AttributeError, OSError):  # pragma: no cover - already UTF-8 or piped
        pass

# Every route must appear exactly this many times in a valid dataset.
CASES_PER_ROUTE = 10

ALL_ROUTES = tuple(route.value for route in Route)

REQUIRED_FIELDS = (
    "id",
    "question",
    "expected_route",
    "expected_steps",
    "expected_requires_freshness",
    "expected_requires_exact_citation",
    "category",
    "difficulty",
)

VALID_DIFFICULTIES = ("normal", "boundary")

# Report gates. These are targets for the current system, not assertions about
# it: falling short is reported and exits non-zero, and is never "fixed" by
# editing the dataset or the planner.
GATE_OVERALL_ACCURACY = 0.90
GATE_MACRO_ACCURACY = 0.90
GATE_PER_ROUTE_ACCURACY = 0.80
GATE_BOUNDARY_ACCURACY = 0.85


def _steps_for_route(route: str) -> list[str]:
    """The canonical step tuple implied by a route name."""
    for steps, known in ROUTE_BY_STEPS.items():
        if known.value == route:
            return [step.value for step in steps]
    raise KeyError(route)


def git_sha() -> str:
    try:
        completed = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=15,
            cwd=Path(__file__).resolve().parent,
        )
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    if completed.returncode != 0:
        return "unknown"
    return completed.stdout.strip() or "unknown"


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


# --------------------------------------------------------------------------
# Dataset validation
# --------------------------------------------------------------------------


def validate_dataset(cases: object, path: Path) -> list[dict]:
    """Reject a malformed dataset before a single plan is computed.

    A silently-skipped or duplicated case would quietly change every metric, so
    every problem is collected and raised together rather than one at a time.
    """
    if not isinstance(cases, list):
        raise ValueError(f"{path}: dataset must be a JSON array")
    if not cases:
        raise ValueError(f"{path}: dataset must not be empty")

    problems: list[str] = []
    seen_ids: dict[str, int] = {}
    seen_questions: dict[str, int] = {}
    route_counts: Counter[str] = Counter()

    for index, case in enumerate(cases):
        where = f"cases[{index}]"
        if not isinstance(case, dict):
            problems.append(f"{where} must be a JSON object")
            continue

        for field in REQUIRED_FIELDS:
            if field not in case:
                problems.append(f"{where}.{field} is required")
        if any(field not in case for field in REQUIRED_FIELDS):
            continue

        case_id = case["id"]
        question = case["question"]
        route = case["expected_route"]
        steps = case["expected_steps"]

        if not isinstance(case_id, str) or not case_id.strip():
            problems.append(f"{where}.id must be a non-empty string")
        elif case_id in seen_ids:
            problems.append(
                f"{where}.id duplicates cases[{seen_ids[case_id]}].id: {case_id}"
            )
        else:
            seen_ids[case_id] = index

        if not isinstance(question, str) or not question.strip():
            problems.append(f"{where}.question must be a non-empty string")
        elif question in seen_questions:
            problems.append(
                f"{where}.question duplicates cases[{seen_questions[question]}]"
            )
        else:
            seen_questions[question] = index

        if route not in ALL_ROUTES:
            problems.append(f"{where}.expected_route is not a known route: {route!r}")
        else:
            route_counts[route] += 1
            if not isinstance(steps, list):
                problems.append(f"{where}.expected_steps must be a list")
            elif steps != _steps_for_route(route):
                # Steps are derivable from the route; storing both is only
                # useful if a disagreement is treated as a data error.
                problems.append(
                    f"{where}.expected_steps {steps} does not match "
                    f"expected_route {route!r} (expected {_steps_for_route(route)})"
                )

        for flag in ("expected_requires_freshness", "expected_requires_exact_citation"):
            if not isinstance(case[flag], bool):
                problems.append(f"{where}.{flag} must be a boolean")

        if not isinstance(case["category"], str) or not case["category"].strip():
            problems.append(f"{where}.category must be a non-empty string")
        if case["difficulty"] not in VALID_DIFFICULTIES:
            problems.append(
                f"{where}.difficulty must be one of {VALID_DIFFICULTIES}, "
                f"got {case['difficulty']!r}"
            )

    for route in ALL_ROUTES:
        actual = route_counts[route]
        if actual != CASES_PER_ROUTE:
            problems.append(
                f"route {route!r} has {actual} cases, expected {CASES_PER_ROUTE}"
            )

    if problems:
        raise ValueError(
            f"{path}: {len(problems)} dataset problem(s):\n  - "
            + "\n  - ".join(problems)
        )
    return cases


# --------------------------------------------------------------------------
# Evaluation
# --------------------------------------------------------------------------


def evaluate_case(case: dict) -> dict:
    plan = plan_request(case["question"])
    actual_route = plan.route.value
    actual_steps = [step.value for step in plan.steps]
    route_ok = actual_route == case["expected_route"]
    steps_ok = actual_steps == case["expected_steps"]
    freshness_ok = plan.signals.requires_freshness == case["expected_requires_freshness"]
    citation_ok = (
        plan.signals.requires_exact_citation == case["expected_requires_exact_citation"]
    )
    return {
        "id": case["id"],
        "question": case["question"],
        "category": case["category"],
        "difficulty": case["difficulty"],
        "notes": case.get("notes", ""),
        "expected_route": case["expected_route"],
        "actual_route": actual_route,
        "expected_steps": case["expected_steps"],
        "actual_steps": actual_steps,
        "expected_requires_freshness": case["expected_requires_freshness"],
        "actual_requires_freshness": plan.signals.requires_freshness,
        "expected_requires_exact_citation": case["expected_requires_exact_citation"],
        "actual_requires_exact_citation": plan.signals.requires_exact_citation,
        "reason_codes": list(plan.reason_codes),
        "fallback_used": plan.fallback_used,
        "route_match": route_ok,
        "steps_match": steps_ok,
        "freshness_match": freshness_ok,
        "exact_citation_match": citation_ok,
        # The headline PASS is route + steps. Signal accuracy is reported
        # separately so a signal gap never hides behind a correct route.
        "passed": route_ok and steps_ok,
    }


def _rate(hits: int, total: int) -> float:
    return hits / total if total else 0.0


def summarize(records: list[dict]) -> dict:
    total = len(records)
    per_route: dict[str, dict[str, int]] = {
        route: {"total": 0, "passed": 0} for route in ALL_ROUTES
    }
    confusion: dict[str, Counter[str]] = defaultdict(Counter)
    boundary_total = boundary_passed = 0

    for record in records:
        expected = record["expected_route"]
        per_route[expected]["total"] += 1
        per_route[expected]["passed"] += record["route_match"]
        confusion[expected][record["actual_route"]] += 1
        if record["difficulty"] == "boundary":
            boundary_total += 1
            boundary_passed += record["route_match"]

    route_accuracy = {
        route: _rate(counts["passed"], counts["total"])
        for route, counts in per_route.items()
    }
    overall = _rate(sum(r["route_match"] for r in records), total)
    macro = sum(route_accuracy.values()) / len(route_accuracy) if route_accuracy else 0.0

    return {
        "total_cases": total,
        "overall_accuracy": overall,
        "macro_accuracy": macro,
        "steps_exact_match": _rate(sum(r["steps_match"] for r in records), total),
        "freshness_signal_accuracy": _rate(
            sum(r["freshness_match"] for r in records), total
        ),
        "exact_citation_signal_accuracy": _rate(
            sum(r["exact_citation_match"] for r in records), total
        ),
        "boundary_total": boundary_total,
        "boundary_accuracy": _rate(boundary_passed, boundary_total),
        "per_route": {
            route: {
                "total": per_route[route]["total"],
                "passed": per_route[route]["passed"],
                "accuracy": route_accuracy[route],
            }
            for route in ALL_ROUTES
        },
        "confusion_matrix": {
            expected: {actual: count for actual, count in sorted(row.items())}
            for expected, row in sorted(confusion.items())
        },
    }


def check_gates(summary: dict) -> list[dict]:
    gates = [
        {
            "name": "Overall Accuracy",
            "value": summary["overall_accuracy"],
            "threshold": GATE_OVERALL_ACCURACY,
        },
        {
            "name": "Macro Accuracy",
            "value": summary["macro_accuracy"],
            "threshold": GATE_MACRO_ACCURACY,
        },
        {
            "name": "Boundary Accuracy",
            "value": summary["boundary_accuracy"],
            "threshold": GATE_BOUNDARY_ACCURACY,
        },
    ]
    for route in ALL_ROUTES:
        gates.append(
            {
                "name": f"Route Accuracy [{route}]",
                "value": summary["per_route"][route]["accuracy"],
                "threshold": GATE_PER_ROUTE_ACCURACY,
            }
        )
    for gate in gates:
        gate["passed"] = gate["value"] >= gate["threshold"]
    return gates


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------


def _flag(value: bool) -> str:
    return "T" if value else "F"


def print_report(records: list[dict], summary: dict, gates: list[dict]) -> None:
    print("=" * 78)
    print("Per-case results")
    print("=" * 78)
    for index, record in enumerate(records, start=1):
        status = "PASS" if record["passed"] else "FAIL"
        print(
            f"{index:03d}. {status} | {record['id']} | {record['difficulty']}\n"
            f"     Q: {record['question']}"
        )
        print(
            f"     route    expected={record['expected_route']:<22}"
            f"actual={record['actual_route']}"
        )
        print(
            f"     steps    expected={'+'.join(record['expected_steps']) or '-':<22}"
            f"actual={'+'.join(record['actual_steps']) or '-'}"
        )
        print(
            f"     signals  freshness exp={_flag(record['expected_requires_freshness'])}"
            f" act={_flag(record['actual_requires_freshness'])}"
            f" {'OK' if record['freshness_match'] else 'MISMATCH'}"
            f" | exact_citation exp={_flag(record['expected_requires_exact_citation'])}"
            f" act={_flag(record['actual_requires_exact_citation'])}"
            f" {'OK' if record['exact_citation_match'] else 'MISMATCH'}"
        )
        print(f"     reasons  {', '.join(record['reason_codes']) or '-'}")

    print()
    print("=" * 78)
    print("Summary")
    print("=" * 78)
    print(f"Total cases                    : {summary['total_cases']}")
    print(f"Overall Accuracy               : {summary['overall_accuracy']:.1%}")
    print(f"Macro Accuracy                 : {summary['macro_accuracy']:.1%}")
    print(f"Steps Exact Match              : {summary['steps_exact_match']:.1%}")
    print(f"Freshness Signal Accuracy      : {summary['freshness_signal_accuracy']:.1%}")
    print(
        f"Exact Citation Signal Accuracy : "
        f"{summary['exact_citation_signal_accuracy']:.1%}"
    )
    print(
        f"Boundary Accuracy              : {summary['boundary_accuracy']:.1%}"
        f" ({summary['boundary_total']} cases)"
    )

    print()
    print("Per-route accuracy")
    for route in ALL_ROUTES:
        entry = summary["per_route"][route]
        print(
            f"  {route:<22} {entry['passed']:>2}/{entry['total']:<3} "
            f"{entry['accuracy']:.1%}"
        )

    print()
    print("Confusion matrix (rows = expected, columns = actual)")
    header = " " * 24 + "".join(f"{route[:10]:>12}" for route in ALL_ROUTES)
    print(header)
    for expected in ALL_ROUTES:
        row = summary["confusion_matrix"].get(expected, {})
        cells = "".join(f"{row.get(actual, 0):>12}" for actual in ALL_ROUTES)
        print(f"  {expected:<22}{cells}")

    failures = [record for record in records if not record["passed"]]
    print()
    print(f"Failures: {len(failures)}")
    for record in failures:
        print(
            f"  - {record['id']} [{record['difficulty']}] "
            f"{record['expected_route']} -> {record['actual_route']}"
        )
        print(f"      {record['question']}")

    print()
    print("Gates")
    for gate in gates:
        status = "PASS" if gate["passed"] else "FAIL"
        print(
            f"  [{status}] {gate['name']:<32} {gate['value']:.1%} "
            f"(>= {gate['threshold']:.0%})"
        )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dataset", required=True, help="Route dataset JSON file")
    parser.add_argument(
        "--output",
        help="Per-case result JSON file (required unless --validate-only)",
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Check the dataset schema and exit without planning anything",
    )
    args = parser.parse_args(argv)

    dataset_path = Path(args.dataset)
    cases = validate_dataset(
        json.loads(dataset_path.read_text(encoding="utf-8")), dataset_path
    )

    if args.validate_only:
        print(f"Schema OK: {dataset_path} ({len(cases)} cases)")
        print(f"Dataset SHA-256: {sha256_of(dataset_path)}")
        return 0

    if not args.output:
        parser.error("--output is required unless --validate-only is given")
    output_path = Path(args.output)
    records = [evaluate_case(case) for case in cases]
    summary = summarize(records)
    gates = check_gates(summary)

    print_report(records, summary, gates)

    payload = {
        "dataset": str(dataset_path),
        "dataset_sha256": sha256_of(dataset_path),
        "git_sha": git_sha(),
        "python_version": platform.python_version(),
        "evaluator": Path(__file__).name,
        "gates": gates,
        "summary": summary,
        "cases": records,
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print()
    print(f"Wrote {output_path}")
    print(f"Dataset SHA-256: {payload['dataset_sha256']}")

    # A failed gate is an evaluation result, not a crashed script.
    return 0 if all(gate["passed"] for gate in gates) else 1


if __name__ == "__main__":
    sys.exit(main())
